# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [32]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [33]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.82813115 0.57844711 0.24960279 ... 0.86688561 0.95792207 0.1795632 ]
 [0.39880293 0.81790846 0.349285   ... 0.76366982 0.17785633 0.71295613]
 [0.82449839 0.85795569 0.42906466 ... 0.02715293 0.74420623 0.39993038]
 ...
 [0.38766099 0.50331145 0.23114716 ... 0.8076106  0.66574591 0.9968127 ]
 [0.00243953 0.32071152 0.79517689 ... 0.50061636 0.96117792 0.95661998]
 [0.07811427 0.03878855 0.05962339 ... 0.40010004 0.07953861 0.38893067]]
[[0.03527245 0.73567195 0.77852369 ... 0.63390175 0.47064549 0.49516448]
 [0.71532769 0.61723802 0.50120809 ... 0.58953227 0.63079703 0.28434235]
 [0.26053985 0.80013516 0.96589062 ... 0.25712842 0.96730897 0.24281082]
 ...
 [0.86367888 0.90615581 0.62270778 ... 0.8632144  0.66802037 0.81055479]
 [0.04606789 0.89675407 0.82931342 ... 0.21862836 0.74307427 0.85606424]
 [0.96497627 0.31246455 0.3936524  ... 0.60388117 0.41332715 0.50899615]]


Без использования numpy

In [36]:
def mult(a, b):
    result=None
    rows_a, cols_a=len(a), len(a[0])
    rows_b, cols_b=len(b), len(b[0])
    result=[[0 for _ in range(cols_b)] for _ in range(rows_a)]
    for i in range(rows_a):
        for j in range(cols_b):
            for k in range(cols_a):
                result[i][j]+=a[i][k]*b[k][j]
    return result

C использованием numpy

In [37]:
def np_mult(a, b):
    result=None
    result=np.dot(a, b)
    return result

In [38]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 727 ms, sys: 0 ns, total: 727 ms
Wall time: 741 ms


In [39]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 1.37 ms, sys: 4.25 ms, total: 5.63 ms
Wall time: 5.28 ms


In [40]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.518429826319334e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [41]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.84456687 0.43952067 0.9617318 ] [0.44804302 0.62059088 0.77197566]


In [42]:
def scalar_product(a,b):
    s=sum(ai * bi for ai, bi in zip(a, b))
    return s

In [43]:
def np_scalar_product(a,b):
    s=np.dot(a, b)
    return s

In [44]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 32 µs, sys: 0 ns, total: 32 µs
Wall time: 35.5 µs
CPU times: user 43 µs, sys: 0 ns, total: 43 µs
Wall time: 47 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** Методы numpy являются более эффективными за счёт эффективного управления памятью, оптимизированнным алгоритмам, векторизованным операциям. В numpy скорость вычислений быстрее, чем при использовании списков и циклов в python, что более заметно при работе со сложными математическими операциями или большими наборами данных.

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [45]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  res = None
  diagonal_elem=np.diagonal(a)
  diagonal_eleme=diagonal_elem[diagonal_elem%2==0]
  res = np.sum(diagonal_elem)
  return res

In [46]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[1, 6, 4, 2, 4],
       [4, 9, 9, 1, 1],
       [5, 6, 8, 8, 6],
       [4, 3, 1, 1, 2],
       [7, 2, 2, 9, 7]])

In [47]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 121 µs, sys: 20 µs, total: 141 µs
Wall time: 146 µs


26

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [48]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
    result = None
    A=np.array(A)
    cumsum_array=np.cumsum(A, axis=1)
    indices=np.arange(1, A.shape[1]+1)
    result=cumsum_array/indices[:, np.newaxis]
    return result

In [49]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[0.32583351 0.98859739 0.28284231 0.31966561 0.37195348 0.42761581
 0.2626717  0.08308149 0.27033187 0.47318926 0.25292587 0.84065168
 0.08140922 0.42828704 0.07445477 0.45940499 0.32087114 0.81056782
 0.65457008 0.26420137 0.31607758 0.75510301 0.93126361 0.52908102
 0.30457614 0.24827059 0.1536063  0.19884407 0.93057431 0.41008029
 0.08332681 0.83066721 0.09097068 0.33938684 0.75838358 0.09761458
 0.35710023 0.28703964 0.39204654 0.39256917 0.35551923 0.08848451
 0.60468833 0.82257926 0.48067558 0.25780855 0.11734283 0.72243563
 0.84047118 0.52049655 0.84666749 0.9676491  0.37700982 0.13802166
 0.11886636 0.799771   0.36882157 0.1586816  0.81994545 0.05231286
 0.72234587 0.790907   0.3923022  0.57155238 0.08791362 0.09046005
 0.18506967 0.81790448 0.92154923 0.19632974 0.03110777 0.55765303
 0.05804227 0.61537995 0.32303573 0.11366483 0.16092882 0.61146328
 0.05145813 0.61955971 0.50464739 0.73095879 0.68318147 0.88173039
 0.25950221 0.49725122 0.37193672 0.49835878 0.61614734 0.7203

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [50]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    result = None
    if len(a)==0:
        return np.array([]), np.array([])
    unique_elem, counts = [a[0]], [1]
    for i in range(1, len(a)):
        if a[i] == a[i-1]:
            counts[-1]+=1
        else:
            unique_elem.append(a[i])
            counts.append(1)
    result = np.array(unique_elem), np.array(counts)
    return result

In [51]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 35 µs, sys: 6 µs, total: 41 µs
Wall time: 44.1 µs


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [52]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    """
    param X: array
    """
    result = None
    result=X.copy()
    result[1::2]=a
    result[0::2]**=3
    result=result[::-1]
    result=np.concatenate((X, result))
    return result

In [53]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 104 µs, sys: 16 µs, total: 120 µs
Wall time: 125 µs
